# Generated by Django 4.0.3 on 2022-03-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('iphone', 'iphone')], max_length=10, null=True),
        ),
    ]
