# Generated by Django 4.0.3 on 2022-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_num',
            field=models.CharField(max_length=50),
        ),
    ]
