# Generated by Django 4.0.3 on 2022-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('iphone', 'iphone'), ('vegetable', 'vegetable')], max_length=10, null=True),
        ),
    ]
